// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJtB2dLDfCj9H9AQOz4Fb-qkQQGjEQqv8',
    appId: '1:847257745:web:c4c2fe0666a8af71c1f03e',
    messagingSenderId: '847257745',
    projectId: 'quiz-war-4257f',
    authDomain: 'quiz-war-4257f.firebaseapp.com',
    databaseURL:
        'https://quiz-war-4257f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-war-4257f.appspot.com',
    measurementId: 'G-YZQJ8YZQJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtB2dLDfCj9H9AQOz4Fb-qkQQGjEQqv8',
    appId: '1:847257745:android:c4c2fe0666a8af71c1f03e',
    messagingSenderId: '847257745',
    projectId: 'quiz-war-4257f',
    authDomain: 'quiz-war-4257f.firebaseapp.com',
    databaseURL:
        'https://quiz-war-4257f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-war-4257f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtB2dLDfCj9H9AQOz4Fb-qkQQGjEQqv8',
    appId: '1:847257745:ios:c4c2fe0666a8af71c1f03e',
    messagingSenderId: '847257745',
    projectId: 'quiz-war-4257f',
    authDomain: 'quiz-war-4257f.firebaseapp.com',
    databaseURL:
        'https://quiz-war-4257f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-war-4257f.appspot.com',
    iosBundleId: 'com.example.quizwar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtB2dLDfCj9H9AQOz4Fb-qkQQGjEQqv8',
    appId: '1:847257745:ios:c4c2fe0666a8af71c1f03e',
    messagingSenderId: '847257745',
    projectId: 'quiz-war-4257f',
    authDomain: 'quiz-war-4257f.firebaseapp.com',
    databaseURL:
        'https://quiz-war-4257f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-war-4257f.appspot.com',
    iosBundleId: 'com.example.quizwar',
  );
}
